# Generated by Django 6.0.1 on 2026-01-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_owner_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('BOAT', 'Boat'), ('MOTORCYCLE', 'Motorcycle'), ('EQUIP', 'Equipment')], max_length=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='e.g. My Street Glide', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
