# Generated by Django 6.0.1 on 2026-01-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_asset_asset_type_alter_asset_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_reading',
            field=models.FloatField(default=0, verbose_name='Current Odometer/Hours'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_service_reading',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='service_interval',
            field=models.FloatField(default=5000, help_text='Alert every X miles/hours'),
        ),
    ]
