# Generated by Django 6.0.1 on 2026-01-31 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_current_reading_asset_last_service_reading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='last_service_reading',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='service_interval',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='use_hours',
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='meter_reading',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='e.g. Oil Change, Spark Plugs', max_length=100)),
                ('interval_miles', models.IntegerField(help_text='Repeat every X miles/hours')),
                ('last_completed_mileage', models.IntegerField(default=0, help_text='Odometer/Hours at last completion')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.asset')),
            ],
        ),
    ]
