# Generated by Django 6.0.1 on 2026-01-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_asset_last_service_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='last_completed_mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='task_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
