# Generated by Django 6.0.1 on 2026-01-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_asset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='interval_miles',
            field=models.IntegerField(default=0, help_text='Repeat every X miles/hours'),
        ),
    ]
