# Generated by Django 6.0.1 on 2026-02-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_maintenancetask_interval_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='primary_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='primary_paint_code',
            field=models.CharField(blank=True, help_text='Manufacturer Paint Code', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='secondary_paint_code',
            field=models.CharField(blank=True, help_text='Secondary/Trim Paint Code', max_length=30, null=True),
        ),
    ]
